### ISSUE TITLE
GEMM output and reference not matching.

### ISSUE THREAD

**Issue by manojrohit** [KastnerRG/spector#4]
Output in Emulation mode.  You can see that the 985728/1048576 are wrong result. 
-------------------Terminal Output-----------------------------
Warning! Device not recognized, using FPGAInitializing the AOC binary files 
Setting up OpenCL...
2 platforms:
  - Intel(R) FPGA SDK for OpenCL(TM)
    with 1 device(s):
      - EmulatorDevice : Emulated Device
  - NVIDIA CUDA
    with 1 device(s):
      - Quadro M4000
Using EmulatorDevice : Emulated Device
Max work items: 2147483647 2147483647 2147483647

----------------------Kernel build log----------------------
Trivial build
------------------------------------------------------------

before kernel starts!

 Launching the Kernel
 Waiting for the Kernel to finish 

 Kernel Execution completedRun-time is:27453.019189 ms 
dse result:
 16, 1, 1, 1, 1, 2, 2, 0,  4, 1372.650959

 Number of elements error: 985728 
Failed:Output does not match the golden out!!!!985728

**Comment by qkgautier** [comment]
I recompiled this particular kernel with AOCL 16.1 and ran it on an FPGA to verify the output, and the output matches the reference in my case. Same when running it on GPU. I'm not sure about the emulator though, I have no experience with it. Maybe an optimization is not interpreted the same way between the emulator and the actual compiler?

**Comment by manojrohit** [comment]
Yeah, even I tried generating the binary files for FPGA. The output matches in FPGA unlike the emulation mode. 
Clear bug in the emulator. Only attributes used are : Work items, Unrolling and SIMD vectorization. 
I think the SIMD optimizer is not interpreted the same way.

**Comment by qkgautier** [comment]
It seems that the compiler is not able to vectorize certain memory transactions, that may be where the difference is. I'm closing this for now as an emulator bug, feel free to reopen if you find an actual bug in the kernel.
